env:
  browser: true
  es2021: true
extends: ["plugin:svelte/recommended", "google"]
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins: [
  'svelte'
]
overrides: [
  {
    files: ['*.svelte'],
    parser: "svelte-eslint-parser",

  }
]
rules: {
  quotes: ['error', 'double'],
  max-len: 0,
  svelte/no-at-html-tags: 0 
}
